---
services:
  api:
    build:
      context: ./api
      target: dev
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:80"
    container_name: api

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - db-data:/var/lib/postgres/data
