---
all:
  children:
    frontend_group:
      hosts:
        frontend:
          ansible_host: "{{ vars }}"
          ansible_user: ubuntu
          ansible_connection: ssh
    backend_group:
      hosts:
        backend:
          ansible_host: "{{ vars }}"
          ansible_user: ubuntu
          ansible_connection: ssh
    database_group:
      hosts:
        database:
          ansible_host: "{{ vars }}"
          ansible_user: ubuntu
          ansible_connection: ssh