name: build and go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET 6.0.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
    
      - name: Install dependencies Basic3tier.Core
        run: dotnet restore ./api/Basic3Tier.Core/Basic3Tier.Core.csproj

      - name: Install dependencies Basic3tier.Infrastructure
        run: dotnet restore ./api/Basic3Tier.Infrastructure/Basic3Tier.Infrastructure.csproj

      - name: Install dependencies Basic3tierAPI
        run: dotnet restore ./api/Basic3TierAPI/Basic3TierAPI.csproj

      - name: Build Basic3tier.Core
        run: dotnet build ./api/Basic3Tier.Core/Basic3Tier.Core.csproj

      - name: Build Basic3tier.Infrastructure
        run: dotnet build ./api/Basic3Tier.Infrastructure/Basic3Tier.Infrastructure.csproj

      - name: Build Basic3tierAPI
        run: dotnet build ./api/Basic3TierAPI/Basic3TierAPI.csproj

      - name: Test Basic3tier.Core
        run: dotnet test ./api/Basic3Tier.Core/Basic3Tier.Core.csproj

      - name: Test Basic3tier.Infrastructure
        run: dotnet test ./api/Basic3Tier.Infrastructure/Basic3Tier.Infrastructure.csproj

      - name: Test Basic3tierAPI
        run: dotnet test ./api/Basic3TierAPI/Basic3TierAPI.csproj
