name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
      - name: Setup .NET 6.0.22
        uses: actions/setup-dotnet@v3
        with:
        # Semantic version range syntax or exact version of a dotnet version
          dotnet-version: '6.0.22'
      - name: Install dependencies
        working-directory: /home/runner/work/3-tier-application/3-tier-application/api
        run: dotnet restore
      - name: Build
        working-directory: /home/runner/work/3-tier-application/3-tier-application/api
        run: dotnet build
      - name: Test with the dotnet CLI
        working-directory: /home/runner/work/3-tier-application/3-tier-application/api
        run: dotnet test